var express = require('express'),
    app = express();
const router = express.Router()

app.set('view engine', 'ejs')

var sessionsDB = require('../models/model')
sessionsDB.setSchema(   {
     eventIDs: [ // array of object IDs
        {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Event"
        }
    ],
    sessionID: String      
   })

var eventsDB = require('../models/model')
eventsDB.setSchema({
        eventName: String,
        startDate: Date,
        endDate: Date,
        time: String,
        subjects: [String],
        eventType: [String],
        image: Sting,
        eventDetails: String,
        price: Number
    })

var usersDB = require('../models/model')
usersDB.setSchema({})

eventsDB.save({}, (err) => {});
sessionsDB.save({}, (err) => {});
usersDB.save({}, (err) => {});


// connect to our model with assigned variable to use inside the controller
// const eventsCollection = mongoose.model("events");
// const sessionCollection = mongoose.model("sessions")


// DUMMY EVENTS
var events = [
    {
        _id: 1, // will be generated by mongoose
        eventName: 'Code workshop',
        startDate: '20/02/2017',
        endDate: '21/02/2017',
        subjects: ['Node.js', 'express.js'],
        eventType: ['evening', 'one day'],
        image: 'https://i2.wp.com/www.barcelonacodeschool.com/wp-content/uploads/2016/04/students-in-classroom.jpg?zoom=1.5&fit=564%2C388',
        eventDetails: 'Details',
        price: 400
    },
    {
        _id: 2, // will be generated by mongoose
        eventName: 'JavaScript Full-Stack Bootcamp',
        eventDetails: '8 weeks, Monday to Friday, from 9:00 till you drop',
        startDate: '22/05/2017',
        endDate: '14/07/17',
        subjects: ['Node.js', 'express.js', 'mongoDB'],
        eventType: ['Three month course'],
        image: 'https://i2.wp.com/www.barcelonacodeschool.com/wp-content/uploads/2016/04/students-in-classroom.jpg?zoom=1.5&fit=564%2C388',
        price: 3000
    }
]

/*GET /events   
Displays the events calendar page
    renders the index.ejs view */
router.get("/events", function(req, res){
    eventsDB.getAll( (err, records) =>{ 
    	if (err) {
    		res.redirect("error", err)
    	} else {
        res.render("index", {events: records}) 
	    }} )
     
})

/*
GET /events/:id
Displays the  selected single event page
    renders the show.ejs
*/
router.get ("/events/:id", function (req, res) {
	eventsDB.getOne(req.params.id, (err, record) => {
		if (err) {
			res.redirect("error", err)
		} else {
			res.render("show", {event: record})
		}
	})
})


/*
POST /cart/:id
- creates new session object
- adds event reference to session object
- creates new cookie with sessionID equal to session._id
- redirects to /cart
*/
router.post("/cart/:id", function(req, res){
    sessionsDB.save({eventIDs: [req.params.id]}, (err, record) =>{
        if (err) {
        	res.redirect("error", err)
        } else {
        res.cookie('sessionID', record._id, { maxAge: 9000000000, httpOnly: false })
        }
    }) 
})


/*    
GET /cart
- displays the events the client has selected
- information about selected tickets and the client is stored in an object ('session')
- renders cart.ejs
*/
router.get("/cart", (req, res) => {
	// if session (from req.cookies.sessionID) exists 
	sessionsDB.getOne(req.cookies.sessionID, (err, records) => {
		if (err) {
			res.redirect("error", err)
		} else {
			//display cart with event associated to the current user
			res.render("cart", records)
		}
	})

})

/*
GET /checkout/
Displays the checkout page for the user with his sessionID
renders the checkout.ejs
args: get, sessionID
*/



module.exports = router



/*
POST /cart/update
Cart page with update the quantity of products
    renders the cart.ejs
args: post, sessionID, amount of products

POST /cart/remove
Cart page with remove the product option
    renders the cart.ejs
args: post, sessionID, remove event

GET /cart/coupon
Cart page with apply the coupon option to get a discount
    renders the cart.ejs
args: get, coupon, discoun

POST /checkout/pay
args: post, sessionID
– saves users billing details in the database
– check if the terms & conditions are checked
– redirects to/process the payment
– redirects back to the root or displays the confirmation page*/